POST http://localhost:8080/chat HTTP/1.1
Content-Type: application/json
Authorization: 123456

{
    "user_id": "1",
    "user_message": "Olá, qual é o seu nome?"
}

###

POST http://localhost:8080/chat HTTP/1.1
Content-Type: application/json
Authorization: 123456

{
    "chat_id": "ed4c9fd4-b8e9-4592-9730-1d25b742daf9",
    "user_id": "1",
    "user_message": "Eu quero saber sobre o conflito armado na palestina, quem são os houthis?"
}