GET http://localhost:3000/api/hello

@token = eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..CEImIwBu5-vdyDaF.cFd2W-l31ItpC7f6mTrzrzd7WsBEViP9oVOVT3bRZM9MzeZ7WWokIj69i1pV2Q0GdWvV0p8FcsYes85sLC9wtteK5VKLX5Z24H0LxPoj8ujTdCvrxZ0sFesuMws-hnhZwbSNCLV91g8JueQaphsyzfbvI3SQFLOIDoeSJI3XLeUr5JEx6H3R0zKdNt8.LVbmjeC9OaHSEfvU29axHw
@chatId = 323c993e-27c2-41cd-a787-4fc1690ac716
###
POST http://localhost:3000/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "message": "Qual sua missão aqui?"
}

###
GET http://localhost:3000/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}
###

GET http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "message": "Estou testando a API Novamente 33"
}

###
@messageId = 7a29937f-c264-4937-b877-53f906919b02
GET http://localhost:3000/api/messages/{{messageId}}/events
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/generate-token
Content-Type: application/json

{

}

###
GET http://localhost:3000/api/event-stream