GET http://localhost:3000/api/hello

@token = eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..o1OCHhHlnHM62H7h.YHrgO4q7XxWm19f5ejyj8y2oVN-s3ftVY4e2J0puW1la1ZeoTjo0q3rjAGn4EwkkiRheHx-Zb85qvKO_vFQuaCJzTo1Kx_kE80NR7oBuOKjEGJdjnUIRD8Ba4J4tn26ZrJQVjgpZKSLqKac6u_U1nUN0aYAGZ-ZW_vCJL7RMSDnU25e83BKPNC3Ld8c.CM26M7P5xFbEwfrEUYlTeQ
@chatId = 323c993e-27c2-41cd-a787-4fc1690ac716
###
POST http://localhost:3000/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "message": "Qual sua missão aqui?"
}

###
GET http://localhost:3000/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}
###

GET http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "message": "Estou testando a API Novamente 33"
}

###
@messageId = 7a29937f-c264-4937-b877-53f906919b02
GET http://localhost:3000/api/messages/{{messageId}}/events
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/generate-token
Content-Type: application/json

{

}

###
GET http://localhost:3000/api/event-stream