GET http://localhost:3000/api/hello

@token = eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..XnskWOEMEV-7teRh.Kfx1uSJGTBQzhMdy_gaDlCNz_Lz9UvSeKBCMBPHdKOZmN-WoZZRkOrFwmdbBDfKjRg7Y48VnP_9-K5xkUP4H6nGeCvc9ovRvuKlGFKm2ja_E3CjYjGLHRFLjrcYIu3qb9YPNYIZ41leztsY20HPbtQ7lyxUjKYwjDKvU3e59hvg8QNjc3dQyglaCvzs.TIHDzzl-FrxwwH3hKFr1Wg
###
POST http://localhost:3000/api/chats
Content-Type: application/json

{
  "message": "Mensagem de texto 2"
}

###
GET http://localhost:3000/api/chats

###
@chatId = b0fffac5-c777-418c-b3d3-690d19e9a7da
GET http://localhost:3000/api/chats/{{chatId}}/messages


###
POST http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json
# Authorization: Bearer {{token}}

{
  "message": "Estou testando a API Novamente 33"
}

###
@messageId = 7a29937f-c264-4937-b877-53f906919b02
GET http://localhost:3000/api/messages/{{messageId}}/events
# Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/generate-token
Content-Type: application/json

{

}

###
GET http://localhost:3000/api/event-stream