version: '3'

services:
  # app:
  #   build: .
  #   ports:
  #     - 3001:3000
  #   volumes: 
  #     - .:/home/node/app

  mysql_fchat:
    image: mysql:8
    container_name: mysql_fchat
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat
    ports: 
      - 3307:3306
    volumes:
      - .docker/dbdata:/var/lib/mysql
      # networks:
      #   - fcexperience